-- IT431 Project 2 — sample schema for the "products" table.
--
-- Paste this into the Supabase SQL Editor, adjust the column list to match
-- your domain (recipes, games, movies, etc.), then run it. You'll need the
-- matching Product type in src/types.ts.

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,

  -- TODO: replace these placeholders with your real fields (at least 5).
  first_name    text    not null,
  last_name   text    not null,
  height    integer   not null,
  weight    integer   not null,
  age   integer   not null
);

-- Row Level Security: the database, not the UI, decides who can do what.
alter table public.players enable row level security;

-- Anyone (including anonymous visitors) can read.
create policy "players_select_anyone"
  on public.players for select
  using (true);

-- Only signed-in users can insert, and they must stamp their own user_id.
create policy "players_insert_authenticated"
  on public.players for insert
  to authenticated
  with check (auth.uid() = user_id);

-- Users can only edit rows they created.
create policy "players_update_owner"
  on public.players for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Users can only delete rows they created.
create policy "players_delete_owner"
  on public.players for delete
  to authenticated
  using (auth.uid() = user_id);